export const GALLERY_IMAGES = [
  {
    id: 1,
    src: "/gallery/1.jpg",
    alt: "Жубайлар 1",
    name: "Бексултан & Тахмина",
    role: "👰‍♀️🤵‍♂️",
    groupIndex: 0,
  },
  {
    id: 2,
    src: "/gallery/2.jpg",
    alt: "Жубайлар 2",
    name: "Бексултан & Тахмина",
    role: "💕 Сүйүү",
    groupIndex: 0,
  },
  {
    id: 3,
    src: "/gallery/3.jpg",
    alt: "Жубайлар 3",
    groupIndex: 0,
    name: "Бексултан & Тахмина",
    role: "💍 Күтүү",
  },
  {
    id: 4,
    src: "/gallery/4.jpg",
    alt: "Жубайлар 4",
    name: "Бексултан & Тахмина",
    role: "✨ Арман",
    groupIndex: 0,
  },
  {
    id: 5,
    src: "/gallery/5.jpg",
    alt: "Жубайлар 5",
    name: "Бексултан & Тахмина",
    role: "🎉 Майрам",
    groupIndex: 1,
  },
  {
    id: 6,
    src: "/gallery/6.jpg",
    alt: "Жубайлар 6",
    groupIndex: 1,
    name: "Бексултан & Тахмина",
    role: "🎉 Майрам",
  },
  {
    id: 7,
    src: "/gallery/7.jpg",
    alt: "Жубайлар 7",
    name: "Бексултан & Тахмина",
    role: "🎉 Майрам",
    groupIndex: 1,
  },
  {
    id: 8,
    src: "/gallery/8.jpg",
    alt: "Жубайлар 8",
    name: "Бексултан & Тахмина",
    role: "🎉 Майрам",
    groupIndex: 1,
  },
  {
    id: 9,
    src: "/gallery/9.jpg",
    alt: "Жубайлар 9",
    name: "Бексултан & Тахмина",
    role: "🎉 Майрам",
    groupIndex: 2,
  },
  {
    id: 10,
    src: "/gallery/10.jpg",
    alt: "Жубайлар 10",
    name: "Бексултан & Тахмина",
    role: "🎉 Майрам",
    groupIndex: 2,
  },
  {
    id: 11,
    src: "/gallery/11.jpg",
    alt: "Жубайлар 11",
    name: "Бексултан & Тахмина",
    role: "🎉 Майрам",
    groupIndex: 2,
  },
  {
    id: 12,
    src: "/gallery/12.jpg",
    alt: "Жубайлар 12",
    name: "Бексултан & Тахмина",
    role: "🎉 Майрам",
    groupIndex: 2,
  },
  {
    id: 13,
    src: "/gallery/13.jpg",
    alt: "Жубайлар 13",
    name: "Бексултан & Тахмина",
    role: "🎉 Майрам",
    groupIndex: 3,
  },
  {
    id: 14,
    src: "/gallery/14.jpg",
    alt: "Жубайлар 14",
    name: "Бексултан & Тахмина",
    role: "🎉 Майрам",
    groupIndex: 3,
  },
  {
    id: 15,
    src: "/gallery/15.jpg",
    alt: "Жубайлар 15",
    name: "Бексултан & Тахмина",
    role: "🎉 Майрам",
    groupIndex: 3,
  },
  {
    id: 16,
    src: "/gallery/16.jpg",
    alt: "Жубайлар 16",
    name: "Бексултан & Тахмина",
    role: "🎉 Майрам",
    groupIndex: 3,
  },
  {
    id: 17,
    src: "/gallery/17.jpg",
    alt: "Жубайлар 17",
    name: "Бексултан & Тахмина",
    role: "🎉 Майрам",
    groupIndex: 4,
  },
];
